services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file: 
      - .env
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db:
    driver: local